CREATE TABLE project.USER
(
	USER_ID int(15) PRIMARY KEY AUTO_INCREMENT,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	EMPLOYEE_ID int(15) NOT NULL,
	PROJECT_ID int(15),
	TASK_ID int(15)
);

CREATE TABLE project.PROJECT
(
	PROJECT_ID int(15) PRIMARY KEY AUTO_INCREMENT,
	PROJECT_NAME VARCHAR(50) NOT NULL,
	START_DATE DATE,
	END_DATE DATE,
	PRIORITY int(3),
	MANAGER_NAME VARCHAR(100)
);

